In [6]:
import librosa
import torchaudio
import soundfile as sf

In [8]:
audio_path = '/mnt/pfs_l2/jieti_team/SFT/hupeng/scripts/audio.mp3'

audio, sr = librosa.load(audio_path, sr=None, duration=80)

output_path = '/mnt/pfs_l2/jieti_team/SFT/hupeng/scripts/audio_80s.mp3'

sf.write(output_path, audio, sr)

In [2]:
wav = '/mnt/pfs_l2/jieti_team/SFT/hupeng/data/en/next_online/online_20250408/wavs/wav_0003/17440439316621358964275700817920.wav'
audio, sr = librosa.load(wav, sr=None)

In [3]:
sr

16000

In [4]:
audio

array([ 0.        ,  0.        ,  0.        , ..., -0.00421143,
       -0.00411987, -0.003479  ], dtype=float32)

In [7]:
audio, sr = torchaudio.load(wav)

/mnt/pfs_l2/jieti_team/SFT/hupeng/tools/anaconda3/anaconda3/envs/data/lib/python3.9/site-packages/torchaudio/_backend/utils.py:213: UserWarning: In 2.9, this function's implementation will be changed to use torchaudio.load_with_torchcodec` under the hood. Some parameters like ``normalize``, ``format``, ``buffer_size``, and ``backend`` will be ignored. We recommend that you port your code to rely directly on TorchCodec's decoder instead: https://docs.pytorch.org/torchcodec/stable/generated/torchcodec.decoders.AudioDecoder.html#torchcodec.decoders.AudioDecoder.
  warnings.warn(
/mnt/pfs_l2/jieti_team/SFT/hupeng/tools/anaconda3/anaconda3/envs/data/lib/python3.9/site-packages/torchaudio/_backend/ffmpeg.py:88: UserWarning: torio.io._streaming_media_decoder.StreamingMediaDecoder has been deprecated. This deprecation is part of a large refactoring effort to transition TorchAudio into a maintenance phase. The decoding and encoding capabilities of PyTorch for both audio and video are being cons

In [9]:
audio

tensor([[ 0.0000,  0.0000,  0.0000,  ..., -0.0042, -0.0041, -0.0035]])

In [10]:
audio.mean(dim=0, keepdim=True)

tensor([[ 0.0000,  0.0000,  0.0000,  ..., -0.0042, -0.0041, -0.0035]])

In [12]:
audio.size()

torch.Size([1, 29440])

In [13]:
29440 / 16000

1.84

In [1]:
import json

file = '/mnt/pfs_l2/jieti_team/SFT/hupeng/llm_data/kimi_style/sft/train/sft_train_semantic_codes.json'
max_len = 0
with open(file, 'r') as f:
    for line in f:
        data = json.loads(line)
        new_len = len(data['conversation'][1]['audio_tokens'])
        if new_len > max_len:
            max_len = new_len
print(max_len)

375
